# .streamlit/secrets.toml
[connections.gsheets]
sturdyDataStrategyV1 = "https://docs.google.com/spreadsheets/d/14veR2u5PFIr8PRm9fyiCVNJNM_gCBt_hHjEAPzhOoi8/edit?usp=sharing"
sturdyDataPpsV1 = "https://docs.google.com/spreadsheets/d/1ie9RDpwB5ECzJgn6dAp1ZkxO1PqA-DQr-5KjPYN_BfM/edit?usp=sharing"
